server:
  port: 8091

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
      bindings:
        input:
          destination: users
  zipkin:
      base-url: http://zipkin:9411/
  sleuth:
      sampler:
        probability: 1
  data:
    mongodb:
      host: mongodb-payment
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
