server:
  port: 8091

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: users
  zipkin:
      base-url: http://localhost:9411/
  sleuth:
      sampler:
        probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
