server:
  port: 8090

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: users
          contentType: application/json

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/