server:
  port: 8090

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka
      bindings:
        output:
          destination: users
          contentType: application/json
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1
  data:
    mongodb:
      host: mongodb-user
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

