server:
  port: 8090

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: users
          contentType: application/json
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

