server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

spring:
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1
  data:
    mongodb:
      host: mongodb-videos