server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1